# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: jekyll-org-mode-converter 0.1.6 ruby lib

Gem::Specification.new do |s|
  s.name = "jekyll-org-mode-converter"
  s.version = "0.1.6"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Tjaart van der Walt"]
  s.date = "2015-01-28"
  s.description = "So you want org-mode support for Jekyll. Write your _posts in org-mode, then add 'gems: [jekyll-org-mode-converter]' to your _config.yml. Thats it!"
  s.email = "github@tjaart.co.za"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.org"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "LICENSE.txt",
    "README.org",
    "Rakefile",
    "VERSION",
    "jekyll-org-mode-converter.gemspec",
    "lib/jekyll-org-mode-converter.rb",
    "test/helper.rb",
    "test/test_jekyll-org-mode-converter.rb"
  ]
  s.homepage = "http://github.com/tjaartvdwalt/jekyll-org-mode-converter"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.5"
  s.summary = "Jekyll converter for org-mode files"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<org-ruby>, [">= 0.9.12"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
    else
      s.add_dependency(%q<org-ruby>, [">= 0.9.12"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_dependency(%q<simplecov>, [">= 0"])
    end
  else
    s.add_dependency(%q<org-ruby>, [">= 0.9.12"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    s.add_dependency(%q<simplecov>, [">= 0"])
  end
end

